// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model.enums;


public enum Blatttyp {

	Pik,

	Herz,

	Karo,

	Kreuz;
};
