@startuml

[SpielregelKomponent] as srlk

[SpielsteuerungKomponent] as ssk

[KartenKomponent] as kk

[Console] as Console

[SpielverwaltungKomponent] as svk

[VirtuellerSpielerKomponent] as vsk

database "maumauDB" {

}

ISpielregelKomponent - srlk

ISpielSteuerungKomponent - ssk

IKartenKomponent - kk

ISpielVerwaltungKomponent  - svk

IVirtuellerSpielerKomponent - vsk

Console -right-> ISpielVerwaltungKomponent

Console -down-> ISpielSteuerungKomponent

Console -down-> IVirtuellerSpielerKomponent

ssk --> ISpielregelKomponent

svk -right-> IKartenKomponent

svk -up-> maumauDB







@enduml