// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package komponenten.karten.export;


public enum Blatttyp {

	Pik,

	Herz,

	Karo,

	Kreuz;
};
